### ISSUE TITLE
Bug: Exception when searching something not found

### ISSUE THREAD

**Issue by hykilpikonna** [CSC207-2022F-UofT/mcpm#73]
Please handle null cases in SearchController to tell the user that no results are found. To be safe, please also return an empty list in SearchByCommand and SearchByName (instead of `map.get(key)`, you can use `map.getOrDefault(key, List.of())`)

<img width="780" alt="image" src="https://user-images.githubusercontent.com/22280294/203630559-ec73828a-9799-451f-ae8c-81f83817b876.png">

**Comment by jerryzhu509** [comment]
fixed in the patch
