### ISSUE TITLE
Not using recursive results while installing dependencies

### ISSUE THREAD

**Issue by MstrPikachu** [CSC207-2022F-UofT/mcpm#86]

**Comment by MstrPikachu** [comment]
... [T]here's still a problem that if a dependency (including the initial plugin) is already installed, the rest of the installation will abort because of the thrown exception. 
In terms of the expected behaviour for the use case, we would want it to skip over these plugins, not to stop the installation.
Taylor suggested that we can return the state of the entire installation. The states could be like this: success and fail. Success is if EVERY installation either succeeds or is skipped because it is already installed (NOT a fail). A fail is if there is an error somehow, for AT LEAST one of the plugins.

You could do something like this (here I will use true and false for success and fail, but you should wrap it with a Record):
```suggestion
        if (searchResult.plugins().isEmpty()) {
             // throw new InstallException(Type.NOT_FOUND);
             return false; // we failed so return false
        }
        
...

       var name = pluginVersion.meta().name();
         List<PluginYml> pluginInstalled = input.pluginTracker().listInstalled();
         for (PluginYml pluginYml : pluginInstalled) {
             if (pluginYml != null && pluginYml.name() != null && pluginYml.name().equals(name)) {
                 return true; // we skip the installed plugin so return true because we did not fail
             }
         }

...

        // 4. Installing the depency of that plugin
         boolean ret = true;
         if (pluginVersion.meta().depend()!= null) {
             for (String dependency:pluginVersion.meta().depend()) {
                 InstallInput dependencyInput = new InstallInput(dependency,
                         SearchPackagesType.BY_NAME,
                         installInput.filePath(),
                         installInput.load());
                 ret &= installPlugin(dependencyInput); // we return true iff ALL installs succeed (do not fail), so we use and
 //                input.pluginTracker().removeManuallyInstalled(name);
             }
         }
         return ret;
```

_Originally posted by @MstrPikachu in https://github.com/CSC207-2022F-UofT/mcpm/pull/56#discussion_r1027693375_

**Comment by MstrPikachu** [comment]
Obviously you can't do &= with a record. But what you can do is:
```suggestion
public record InstallResult
{
    State state, // this corresponds to whether failedPlugins is empty or not
    Collection<PluginModel> failedPlugins;
    public enum State {
        SUCCESS,
        FAILED
    }
    public void merge(InstallResult other) {
        if (this.state == State.SUCCESS && other.state == State.SUCCESS) {
            return;
        }
        state.State = State.FAILED;
        failedPlugins.addAll(other.failedPlugins);
}
```
and then in the install method:
```suggestion
        // 4. Installing the depency of that plugin
         InstallResult ret = new InstallResult(InstallResult.State.SUCCESS, List.of());
         if (pluginVersion.meta().depend()!= null) {
             for (String dependency:pluginVersion.meta().depend()) {
                 InstallInput dependencyInput = new InstallInput(dependency,
                         SearchPackagesType.BY_NAME,
                         installInput.filePath(),
                         installInput.load());
                 ret.merge(installPlugin(dependencyInput)); // we return true iff ALL installs succeed (do not fail), so we use and
 //                input.pluginTracker().removeManuallyInstalled(name);
             }
         }
         return ret;
```

_Originally posted by @MstrPikachu in https://github.com/CSC207-2022F-UofT/mcpm/pull/56#discussion_r1027707873_

**Comment by thudoan1706** [comment]
Thank you for pointing the problem out and providing the suggestion XD I also wonder if you have pulled the main to have the recent update version since I moved this to the database manager class. 
      
         var name = pluginVersion.meta().name();
         List<PluginYml> pluginInstalled = input.pluginTracker().listInstalled();
         for (PluginYml pluginYml : pluginInstalled) {
             if (pluginYml != null && pluginYml.name() != null && pluginYml.name().equals(name)) {
                 return true; // we skip the installed plugin so return true because we did not fail
             }
         }

I haven't figured out a way to avoid a plethora of installResult types, so I just moved around with the conditional statement for the install method for now. It seems to fix the issue, but please feel free to check if there is another problem arises (I am sure install method looks like a spaghetti now)

**Comment by MstrPikachu** [comment]
What you could do is in your InstallResult class is have a bunch of lists with all the failure plugins for different types of failures. 
For example you can have a list for plugins with no version available, plugins that are already installed, and a list of plugins that failed to get loaded. Then when you want to merge InstallResult objects, you merge the lists together.
